language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: true

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: alexbahnisch
  password: wT4R0Gf/GcBvad6B47kpYE5VgTBODxR365fO+DO6JnokIQNaQFzhDTgPFq9FUHz+yc/u+FbmiBnsmACLVwNBZhMAiU/4peO2Yqvkp+d1AixmHLF/1hKe4vvDByb6h7955f9ktzJxx2DtUJmlt5IbkV3zSCsY0egotzlvvnKuzyUoHCwZuhyPcsWl+tOd9B7Sk3NFsnKTLBzz0nsqsceyp1IbUrul0prwZoalXKPUhonwvF7gTRyxtKjJ/pOtoOvuNK3ZHzw/QJENc0nFr+2yYfvvDdKN6+gE6Br1u1zCvUF102TSbr5f9tnECnVYBPNxVyiuUSsfwHRWLKS99TwIV6TAJJXESHdMh9XVjHOBmhnkxi1m/EfwLZFDTF2/QCor8ciA56tu3iRZwUnAsJkPvFIW7npAAJH3nd5Q9OmbVpn01Qsw6ltToAHH/21KNZq5D8s06BTJGvsFHWtD5IOyU9/hRNAbe4boCgJoDi+6dzV5b33pHoe9wZsS92ydroXdkZWMLTI2UcOnRp6x9oFItNv+mZ7JTeD5XoTD569qOlBszFRRF0jxQk5Ylzb+jBNNA4jz+LXGYnoe/Eetpnyc7tmZPnEE9b1gEJMsHcN0hQ+UyWBN2jXjyf6EdQ0BShk2SprvB+tUFHp6I1NF2F7u8XdjjTsnD4mxixIJMBZ0J7qE=
  distributions: sdist bdist_wheel
  on:
    branch: master
    python: 3.6
    tags: false
