language: python
python:
- 2.7
- 3.5
- 3.6
install:
- pip install tox-travis
script:
- tox
notifications:
  email: true
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  user: alexbahnisch
  password:
    secure: 0sePx9yKkUnjodNKrQ1LMSOGrtd8DYeckuERgcVnsm7M712+mDWxOy2lAHQhV+HNHH8fMIZojg6V+QL4kKagEQnecL8re3LcU+a+Mq4YGtNoT9f0CajEqo7LBh7R06+PsydZTZ3WIec6C7zSgBMecp6Wwv5D29PgR7j4tAUrOD3c8zRL9sfsnMHaXZOmOnGQP67qzC7LbtQCR9qH4HFZMzSlEax0VTLfH9E8GhMUQVALJCY+szZugeS1nfzXzeHS37VNNW1cqv7RakB19qabbrhTO28hbETBeLlrhfKzo9nUjtBG6vdms1WN9zihPWkpWcrmGSeN65o1kUNGeaFNCD/1CIq4uQ1ljeTWNPdZu5lSDunW51jTGK0Bbg0ZNw+RAEIOAJbaqSSuvWGROF6kfVhUPZxDdzbqqrBQjglyDkoZLo5Utdovs/YW4AjTpyC9kjjk0ucZX+dDO/zkbRbFxG8GMViH4vJj3mpWpDIgNioxlsr0bpdCWU5pSRkdzVP/LOXtMOO6yXhrFNBCDqE30kdg1ga8/p4gq8phpa+v9xqvcHqGF0u/muzXIiEfDHIrkykodj03XqaEgtBWhHswY2g+K5dMz1EWGjcJc4JE6BQzuiE8IebXdR8Cu/IzB3dujIYvNjpiFXSS9FS4cF0Z5GW8Owr4BdbwDlmPRwSbhS0=
  on:
    branch: master
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
