language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: true

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: alexbahnisch
  password: password12345678
  distributions: sdist bdist_wheel
  on:
    branch: master
    python: 3.6
    tags: false
