language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: true

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: alexbahnisch
  password:
    secure: R/aoB9/5dgX9kOJHJu59PeqXbyAGGfMNcq3Mvo5L/1u0v4ZYu+phSPSImPdTCfrt5PGqceS+bo5IBkZspJ7zLhR+8si4E492xv9pa8yo59t8xmUGmIl8tOMK+6ABu7s6fj1qeZxZBjgBTr9d5VWl8nGtb+8/OvGJyq5l/kp7X/r3mxbCDBOl5h/3DuMhZGtZp2dMIv1SmwesoN2gM56g8cVC3b0FBUb/Ul970/F6H/s3ZFbaqN4xtyBs7FxjrGrpFrNs/eX8+JW0F/f9L2U5YOi3zMKg7Puio8drMEHmE3EIEcqpCys/vXJSq8M2YFZ/1+PNHPXMjPDuABQV6iwhAK9E6dmddslmymN6+TqvWmsgljjO6bQykMmmdi+CdwZFKuMJkgx08+Bz2634IpNXzcPeiOp2H108DyS/GdvizVOdm/sWvYf6kXRzDwklhDS7MfeNLz1lxfwQCN9/TSrScWcbfMKgpO0+saLd9fP+sDgVVwRN5BBXAJdkHvG4grM3BWG5ETPyq/XQd9IbcHDtaoemHcmqMJx8SrNg0RJhWL4qQCtpMqZWB2+QgoIGhnM4oMYxlWJZ5VeJ0oc1aX/AeSITNSpVuglCoCt+fequRZOy02Gs2CReB768iZGyhhPaLGabN68R1PmdHvIZbStTZRvbdvjnU0w9EyaZXYH3emY=
  distributions: sdist bdist_wheel
  on:
    branch: master
    python: 3.6
    tags: false
