#sudo: false

language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: true

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: alexbahnisch
  password:
    secure: 4ehaewZzYT/XQhFnDotr03k1QhrdA5TZ87CH1Urs3trV44LnUnSUGnRI2UsAQfJRx5z4ogjKbbP0cqV7W2xPZ7HKBS2PXdkAhQhFRRNF9/AWmgTuBP2U7iW+IRvz94xEqxnARAgxY+oNJtbBIksDfRZIsM2Sv+rlaRquyBYKJku5Iwp7wocrRWmyxSOFf9yHOASMesJ8gLpN0PA6oCYyOG9JzT2dAUcHvk62C4w/smtrumHRQf7xAAR7bbhT7/KPRSAKeXhtbnsjFBvrzluXGUPBKfA/KGvXbJl1ppFnLr3bZOL71bb4N9Py0T5K2ug9trbjEEPNaBN4/eiG+jZKp/ik62h5Pu/kqkvs0wBijE8w57NjNfIxLxxD9wrrSo8T6MHcbdYKE3vYkq9rFysLW23lbZbnb+2Y5QzKbcusF3TSK+BQKO3LRY+JW1Gdmm0d3GGXJ+dEuMWQTub3EbEd+AaGXKUPQrAmVKAcYVeh1fKlUV/gEJVjvameoeyw38pSdoPAB+Ue1X3XfVlO/ajB/E3UV8ILlW1CDhsDmh1UiE0rLixTsumBcBidUsTDHremB+8I1DSOMRxELFKMWmWlG/1+o3XtxY7wJll0MXJRquIG9BYxGy9XxXiEPTN4ntLToBEV5ZA14drf0zkIzQCHEnu0624zcOnpMJYQyuQqfKc=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: false
    python: 3.6
