language: python
python:
- 2.7
- 3.5
- 3.6
install:
- pip install tox-travis
script:
- tox
notifications:
  email: true
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  user: alexbahnisch
  password:
    secure: MWyCs0H9To2SLGjLRgLlW1J+lP+2tRA1SMnpB648y86WIKQWSXf4VPLukxDCWxdaBs0U7Txaz41xuboyUiEZBvrQj6vD6yz2g0s+VtLB582dJO3bnQ+v7aluH+btghkq2WkNSkOaISYpSXuVF2d45tDC/eRdSPHVw7IjALIvor2jUM/7RkEE0kWCHpEJNN53zwonGYvI0TAzRi0G35UHvOa1kECtOrQbYEmgqAjlk15edIk/nixTuaeu1aTNWhkpMoPcDunaWnazwc3GzHlAuneB9bxYTfJxGe8y+bWIw9lyvdjFnSVaWg+zG41fnr3qbeOQXyvHQzaULKyDHkyhaDR0qTvjw5ZwfdPKYg/NIaAnGWDGVnA9zmg+7G75EXQUAmoVazwzPrsRWq6b94HWJQOSNgCj3mo+eE9PViLhnjy0dzsLOhhmWK53O8x/FqMZcTdonrGAkEG/utU5CcCUeLBJXb8pbblCxccj6M/o354Sv8X1q9VlwAkjO/K1K51OzYEHfhT8H+Uie+qwECoImJ3vMbcdF57ENosmikrA8ZSpSt6ooKjdykFJzU/8YpTdYXFJx3g4lRfkmxIX/p81ds1BicgLtwLbi+SnjwIraxeAQw+ux32tt0c4CGxKkyFDHc1NQKJSpDqiiE9fhmDktJ8IbVhnXPbDyhXOkG9VTG0=
  on:
    branch: master
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
