language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: true

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: alexbahnisch
  password:
    secure: 3OFLbwfqjbt+BsAPmZq21nf0seoaAHu7QE0TRvgqHY5fM8GcehCh01TYlDToYhu8rbaeZSqCilWABhiY0v9tTpgrBb7eYkzpg4PBb3LhBLWnxspd1utRTPs3xFCm4j7mnpmwQMnB7sSCcnSE/5gGnebu96+3WgBcJJKiCKwuxfJ1NFDu1CknITT5EXJ3rRlz2WiAHHmTOVy+GI9ZeG1LTvI510ZodKpueTkIKKLFhdyi96twNQRBqQPNx1wUbzNP5cinYJddM2/dtFOwcmu/zfaze8eX1aL4/38tbkY7KRoD/E4Txw9FVp1S2T9+LRGwc02oHZ9Rw9XbB1kgV2wFb53M9aIaQXJLSEWXw3wvQKvFVLSaCOf6K1QFpfJWElAatknxewyLnrHJeqYH+RkIU3xjzaDzUES2T92CeaTq8LxNmOCs8wyhL/TtFfr+33d2NruEWQMINWQu5Y0fAop/x6rQ54KJkce6xOE54WDKppDYlxJzCwCTriB6d2Dvd4Dmnr/jr4z3DcgvU1lO4Qd0v+XERtVCqkY4gGHOgJFvMIqrfIKgjkh5hK2Eyh4ZW667qo+bnYcfOwFO6l+83cbD9AKYsw+avjetE7vUAgTIYqc5G6spqop+mIkFYzrd8I63aWqo5dOYKWrrJpf64JkTjpKv72KEmTiCpbdgovgB+QA=
  distributions: sdist bdist_wheel
  on:
    branch: master
    python: 3.6
    tags: false
